import {SquareView as SquareView0} from "./views/SquareView.js";
import {PieceView as PieceView1} from "./views/PieceView.js";
import {CoordinateView as CoordinateView2} from "./views/CoordinateView.js";
import {BoardView as BoardView3} from "./views/BoardView.js";
import {WhiteRook as WhiteRook4} from "./pieces/WhiteRook.js";
import {WhiteQueen as WhiteQueen5} from "./pieces/WhiteQueen.js";
import {WhitePawn as WhitePawn6} from "./pieces/WhitePawn.js";
import {WhiteKnight as WhiteKnight7} from "./pieces/WhiteKnight.js";
import {WhiteKing as WhiteKing8} from "./pieces/WhiteKing.js";
import {WhiteBishop as WhiteBishop9} from "./pieces/WhiteBishop.js";
import {BlackRook as BlackRook10} from "./pieces/BlackRook.js";
import {BlackQueen as BlackQueen11} from "./pieces/BlackQueen.js";
import {BlackPawn as BlackPawn12} from "./pieces/BlackPawn.js";
import {BlackKnight as BlackKnight13} from "./pieces/BlackKnight.js";
import {BlackKing as BlackKing14} from "./pieces/BlackKing.js";
import {BlackBishop as BlackBishop15} from "./pieces/BlackBishop.js";
import {useFenBoard as useFenBoard16} from "./hooks/useFenBoard.js";
import {useBoardRenderers as useBoardRenderers17} from "./hooks/useBoardRenderers.js";
import {withDraggablePieces as withDraggablePieces18} from "./hocs/withDraggablePieces.js";
import {withClickableSquares as withClickableSquares19} from "./hocs/withClickableSquares.js";
import {ChessBoard as ChessBoard20} from "./ChessBoard.js";
import {DraggableBoard as DraggableBoard21} from "./boards/DraggableBoard.js";
import {DraggableAndClickableBoard as DraggableAndClickableBoard22} from "./boards/DraggableAndClickableBoard.js";
import {ClickableBoard as ClickableBoard23} from "./boards/ClickableBoard.js";
import {Board as Board24} from "./boards/Board.js";

export const SquareView = SquareView0;
export const PieceView = PieceView1;
export const CoordinateView = CoordinateView2;
export const BoardView = BoardView3;
export const WhiteRook = WhiteRook4;
export const WhiteQueen = WhiteQueen5;
export const WhitePawn = WhitePawn6;
export const WhiteKnight = WhiteKnight7;
export const WhiteKing = WhiteKing8;
export const WhiteBishop = WhiteBishop9;
export const BlackRook = BlackRook10;
export const BlackQueen = BlackQueen11;
export const BlackPawn = BlackPawn12;
export const BlackKnight = BlackKnight13;
export const BlackKing = BlackKing14;
export const BlackBishop = BlackBishop15;
export const useFenBoard = useFenBoard16;
export const useBoardRenderers = useBoardRenderers17;
export const withDraggablePieces = withDraggablePieces18;
export const withClickableSquares = withClickableSquares19;
export const ChessBoard = ChessBoard20;
export const DraggableBoard = DraggableBoard21;
export const DraggableAndClickableBoard = DraggableAndClickableBoard22;
export const ClickableBoard = ClickableBoard23;
export const Board = Board24;
